# FROM arm32v7/python:3.7-slim-buster
FROM balenalib/raspberry-pi-debian-python:3.7.4

WORKDIR /app

RUN apt-get update && \
    apt-get install sense-hat -y

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]